#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 03 14:08:11 SAST 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim testBench_behav -key {Behavioral:sim_1:Functional:testBench} -tclbatch testBench.tcl -view /home/SCHROR002/Xilinx/Practical_3_2/Prac3_2_Code/prac3_2_code.srcs/sim_1/imports/Prac3_2_Code/testBench_behav.wcfg -log simulate.log"
xsim testBench_behav -key {Behavioral:sim_1:Functional:testBench} -tclbatch testBench.tcl -view /home/SCHROR002/Xilinx/Practical_3_2/Prac3_2_Code/prac3_2_code.srcs/sim_1/imports/Prac3_2_Code/testBench_behav.wcfg -log simulate.log

